In [2]:
import numpy as np

In [4]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [6]:
a = a.reshape(2, 3, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
a.shape  # This will show the shape of the reshaped array

(2, 3, 4)

In [8]:
a.ndim

3

In [10]:
# spliting 
arr_shlit = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_shlit)

[[1 2 3]
 [4 5 6]]


In [12]:
np.hsplit(arr_shlit, 3) # This line has a typo; it should be no.hsplit


[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [15]:
np.vsplit(arr_shlit, 3) # This line has a tyop; it should be no.vsplit

ValueError: array split does not result in an equal division

In [16]:
a = np.array([1, 2, 3, 4])
v = a.view()
v[0] = 10
print(a) # This will print [10 2 3 4], showing that the original array is affected by the view

[10  2  3  4]


In [20]:
def sub(x, y = 3):
    return x - y
print(sub(10, 1)) # This will print 9, as it subtracts 1 from 10

9


In [21]:
q =np.array([[1, 2, 3],[4, 5, 6]])
r = np.array([10, 20, 30])
print(q + r)  # This will add the array r to each row of q

[[11 22 33]
 [14 25 36]]


In [22]:
arrx = np.array([10, 20, 30, 40, 50])
print(arrx)

[10 20 30 40 50]


In [23]:
arrx[[1, 2, 3]]

array([20, 30, 40])

In [24]:
index = [1, 2, 3]

In [25]:
arrx[index]

array([20, 30, 40])

In [26]:
a = np.array([10, 20, 30, 40, 50])
mask = a > 25
print(a[mask]) # This will print [30 40 50], as these are the elements greater than 25

[30 40 50]
